### ISSUE TITLE
DRAM fails in Pfam step

### ISSUE THREAD

**Issue by erikrikarddaniel** [shafferm/DRAM#2]
Hi,

After two hours of execution, I get this error message:

2020-02-20 09:01:34.157973: Annotation started
0:00:00.015948: 293 fastas found
0:00:00.200998: Retrieved database locations and descriptions
0:00:00.201027: Annotating OX3.63.fa.edit
0:00:00.204969: Filtering fasta
0:00:00.567192: Calling genes with prodigal
0:01:02.343928: Turning genes from prodigal to mmseqs2 db
0:01:05.671204: Getting hits from kofam
0:17:22.857032: Getting forward best hits from uniref
1:59:58.829147: Getting reverse best hits from uniref
2:01:09.718439: Getting descriptions of hits from uniref
2:02:49.837900: Getting forward best hits from peptidase
2:03:04.585179: Getting reverse best hits from peptidase
2:03:10.425246: Getting descriptions of hits from peptidase
2:03:13.396760: Getting hits from pfam
Traceback (most recent call last):
  File "/home/daniel/miniconda3/envs/dram/bin/DRAM.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/domus/h1/daniel/dev/DRAM/scripts/DRAM.py", line 172, in <module>
    args.func(**args_dict)
  File "/domus/h1/daniel/dev/DRAM/mag_annotator/annotate_bins.py", line 871, in annotate_bins
    genes_called, threads, verbose))
  File "/domus/h1/daniel/dev/DRAM/mag_annotator/annotate_bins.py", line 741, in annotate_fasta
    db_handler=db_handler, threads=threads, verbose=verbose))
  File "/domus/h1/daniel/dev/DRAM/mag_annotator/annotate_bins.py", line 192, in run_mmseqs_pfam
    str(threads)], verbose=verbose)
  File "/domus/h1/daniel/dev/DRAM/mag_annotator/utils.py", line 34, in run_process
    stderr=stderr).stdout.decode(errors='ignore')
  File "/home/daniel/miniconda3/envs/dram/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['mmseqs', 'search', 'annotation/working_dir/OX3.63.fa.edit/tmp/gene.mmsdb', '/crex/proj/sllstore2017037/nobackup/data/DRAM_data/pfam.mmspro', 'annotation/working_dir/OX3.63.fa.edit/tmp/pfam.mmsdb', 'annotation/working_dir/OX3.63.fa.edit/tmp/tmp', '-k', '5', '-s', '7', '--threads', '16']' returned non-zero exit status 1.

**Comment by shafferm** [comment]
Hey another one! Thanks for testing. You are only the second group outside our lab to test so this is very helpful in finding the bugs outside our usual setups.

Can you send me the results of `DRAM.py print_config` and also try running the command where it failed directly to see if running MMseqs2 directly gives a more informative error message? The command is `mmseqs search annotation/working_dir/OX3.63.fa.edit/tmp/gene.mmsdb /crex/proj/sllstore2017037/nobackup/data/DRAM_data/pfam.mmspro annotation/working_dir/OX3.63.fa.edit/tmp/pfam.mmsdb annotation/working_dir/OX3.63.fa.edit/tmp/tmp -k 5 -s 7 --threads 16`.

**Comment by erikrikarddaniel** [comment]
DRAM.py print_config:

KEGG db location: None
KOfam db location: /crex/proj/sllstore2017037/nobackup/data/DRAM_data/kofam_profiles.hmm
KOfam KO list location: /crex/proj/sllstore2017037/nobackup/data/DRAM_data/kofam_ko_list.tsv
UniRef db location: /crex/proj/sllstore2017037/nobackup/data/DRAM_data/uniref90.20200215.mmsdb
Pfam db location: /crex/proj/sllstore2017037/nobackup/data/DRAM_data/pfam.mmspro
dbCAN db location: /crex/proj/sllstore2017037/nobackup/data/DRAM_data/dbCAN-HMMdb-V7.txt
RefSeq Viral db location: /crex/proj/sllstore2017037/nobackup/data/DRAM_data/refseq_viral.20200215.mmsdb
MEROPS peptidase db location: /crex/proj/sllstore2017037/nobackup/data/DRAM_data/peptidases.20200215.mmsdb
VOGDB db location: /crex/proj/sllstore2017037/nobackup/data/DRAM_data/vog_latest_hmms.txt
Description db location: /crex/proj/sllstore2017037/nobackup/data/DRAM_data/description_db.sqlite
Genome summary form location: /crex/proj/sllstore2017037/nobackup/data/DRAM_data/genome_summary_form.20200215.tsv
ETC module database location: /crex/proj/sllstore2017037/nobackup/data/DRAM_data/etc_mdoule_database.20200215.tsv
Function heatmap form location: /crex/proj/sllstore2017037/nobackup/data/DRAM_data/function_heatmap_form.20200215.tsv
AMG database location: /crex/proj/sllstore2017037/nobackup/data/DRAM_data/amg_database.20200215.tsv

Attaching stdout and stderr from mmseqs command:

[mmseqs_search.out.txt](https://github.com/shafferm/DRAM/files/4231702/mmseqs_search.out.txt)

**Comment by shafferm** [comment]
This is not an easy one. Could you try upgrading your mmseqs2 install and seeing if that helps? Do the upgrade and then try rerunning the mmseqs2 command. Run `conda upgrade mmseqs2` inside your DRAM conda environment.

**Comment by erikrikarddaniel** [comment]
OK. I upgraded to 11.e1a1c, but now it wants me to update the index -- can you give me a command for that? Building the whole database took forever so I'd prefer not to do it again.

**Comment by shafferm** [comment]
`mmseqs createindex /crex/proj/sllstore2017037/nobackup/data/DRAM_data/pfam.mmspro tmp -k 5 -s 7` is the command. If this fixes the problem then we will likely need to remake indexes for the other mmseqs2 databases as well.

**Comment by erikrikarddaniel** [comment]
I suppose that, now that I've upgraded, I'll to need reindex everything anyway and since this requires me to submit a job to the cluster I might as well do all in one go overnight, but I can only find one file ending with .mmspro.

**Comment by shafferm** [comment]
I only use mmseqs2 on the blast style searches (uniref, merops etc) and on the PFAM hmm style search. Other databases don't make full alignments as easily accessible. So it is the `.mmspro` and `.mmsdb` files which would need to be reindexed. Or you can fully rerun setup. 

Also in case issues like this happen again you can use the `--keep_database_files` flag as part of `prepare_databases`. Then you can pass file directly locations to `prepare_databases` in the future so you don't need to redownload things again.

**Comment by erikrikarddaniel** [comment]
Reindexing fails:

```
Database pfam.mmspro needs header information.
pfam.mmspro_h is missing.
```

The `pfam.mmspro_h` exists; symlink to `pfam.mmspro_seq_h`.

I tried by cding into the directory too.

**Comment by shafferm** [comment]
Seems like you need to start from the beginning again to me. You can do that by running `prepare_databases` again or here is a quick script to do it for pfam only:
```
wget ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.full.gz
mmseqs convertmsa Pfam-A.full.gz pfam.mmsmsa
mmseqs msa2profile pfam.mmsmsa pfam.mmspro --match-mode 1
mmseqs createindex pfam.mmspro tmp -k 5 -s 7
mmseqs search annotation/working_dir/OX3.63.fa.edit/tmp/gene.mmsdb pfam.mmspro result tmp -k 5 -s 7
```

**Comment by erikrikarddaniel** [comment]
OK. I restarted the database preparation, and will rerun classification right after that.

**Comment by erikrikarddaniel** [comment]
This time the database preparation failed after circa two hours. Last lines of the log:

```
2020-02-21 02:02:33 (7,55 MB/s) - ‘DRAM_data/database_files/amg_database.20200221.tsv’ saved [19963/19963]

downloading ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.full.gz
downloading ftp://ftp.ncbi.nlm.nih.gov/refseq/release/viral/viral.1.protein.faa.gz
downloading ftp://ftp.ncbi.nlm.nih.gov/refseq/release/viral/viral.2.protein.faa.gz
downloading https://raw.githubusercontent.com/shafferm/DRAM/master/data/genome_summary_form.tsv
downloading https://raw.githubusercontent.com/shafferm/DRAM/master/data/module_step_form.tsv
downloading https://raw.githubusercontent.com/shafferm/DRAM/master/data/etc_module_database.tsv
downloading https://raw.githubusercontent.com/shafferm/DRAM/master/data/function_heatmap_form.tsv
downloading https://raw.githubusercontent.com/shafferm/DRAM/master/data/amg_database.tsv
Traceback (most recent call last): 
  File "/home/daniel/miniconda3/envs/dram/bin/DRAM.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/domus/h1/daniel/dev/DRAM/scripts/DRAM.py", line 172, in <module>
    args.func(**args_dict)
  File "/domus/h1/daniel/dev/DRAM/mag_annotator/database_processing.py", line 485, in prepare_databases
    set_database_paths(**output_dbs, update_description_db=True)
  File "/domus/h1/daniel/dev/DRAM/mag_annotator/database_processing.py", line 362, in set_database_paths
    populate_description_db(db_dict)
  File "/domus/h1/daniel/dev/DRAM/mag_annotator/database_processing.py", line 382, in populate_description_db
    db_handler)
  File "/domus/h1/daniel/dev/DRAM/mag_annotator/database_processing.py", line 328, in check_exists_and_add_to_description_db
    db_handler.add_descriptions_to_database(description_list, name, clear_table=True)
  File "/domus/h1/daniel/dev/DRAM/mag_annotator/database_handler.py", line 32, in add_descriptions_to_database
    self.session.bulk_save_objects([description_class(**i) for i in description_list])
  File "/home/daniel/miniconda3/envs/dram/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2720, in bulk_save_objects
    False, 
  File "/home/daniel/miniconda3/envs/dram/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2908, in _bulk_save_mappings
    transaction.rollback(_capture_exception=True)
  File "/home/daniel/miniconda3/envs/dram/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/daniel/miniconda3/envs/dram/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/home/daniel/miniconda3/envs/dram/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2902, in _bulk_save_mappings
    render_nulls,
  File "/home/daniel/miniconda3/envs/dram/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 102, in _bulk_insert
    bookkeeping=return_defaults,
  File "/home/daniel/miniconda3/envs/dram/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1084, in _emit_insert_statements
    c = cached_connections[connection].execute(statement, multiparams)
  File "/home/daniel/miniconda3/envs/dram/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/home/daniel/miniconda3/envs/dram/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/daniel/miniconda3/envs/dram/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/home/daniel/miniconda3/envs/dram/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/daniel/miniconda3/envs/dram/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1478, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/home/daniel/miniconda3/envs/dram/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/home/daniel/miniconda3/envs/dram/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/home/daniel/miniconda3/envs/dram/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
OverflowError: string longer than INT_MAX bytes
```

**Comment by smdabdoub** [comment]
Was just about to create an issue, glad I checked here first. We've been having this exact error with prepare_databases from a new install.

**Comment by shafferm** [comment]
Looks like there is at least one ID in uniref that is now longer than 20 characters. Must have been added since I last updated my DRAM databases a week ago. I upped the max length to 40 characters which should fix that issue.

All of your processed databases should be present in our output folder from `prepare_databases`. You should only need to run `DRAM.py set_database_locations` with the locations of all the processed files in your `prepare_databases` output directory and with the `--update_description_db` flag. This will still likely take at least an hour but only will use 1 processor and a limited amount of memory. You need to pass all of the database locations requested by that function in order to get full descriptions of all annotations.

As an example of what those processed databases file names will look like an example `print_config` output is below.

If you have the time and don't want to deal with setting all of those locations manually then you can rerun `prepare_databases` again.

```
KEGG db location: /fs/byo/wrighton-data2/home2/projects/DRAM/DRAM_dbs_20200214/kegg.20200215.mmsdb
KOfam db location: /fs/byo/wrighton-data2/home2/projects/DRAM/DRAM_dbs_20200214/kofam_profiles.hmm
KOfam KO list location: /fs/byo/wrighton-data2/home2/projects/DRAM/DRAM_dbs_20200214/kofam_ko_list.tsv
UniRef db location: /fs/byo/wrighton-data2/home2/projects/DRAM/DRAM_dbs_20200214/uniref90.20200215.mmsdb
Pfam db location: /fs/byo/wrighton-data2/home2/projects/DRAM/DRAM_dbs_20200214/pfam.mmspro
dbCAN db location: /fs/byo/wrighton-data2/home2/projects/DRAM/DRAM_dbs_20200214/dbCAN-HMMdb-V7.txt
RefSeq Viral db location: /fs/byo/wrighton-data2/home2/projects/DRAM/DRAM_dbs_20200214/refseq_viral.20200215.mmsdb
MEROPS peptidase db location: /fs/byo/wrighton-data2/home2/projects/DRAM/DRAM_dbs_20200214/peptidases.20200215.mmsdb
VOGDB db location: /fs/byo/wrighton-data2/home2/projects/DRAM/DRAM_dbs_20200214/vog_latest_hmms.txt
Description db location: /fs/byo/wrighton-data2/home2/projects/DRAM/DRAM_dbs_20200214/description_db.sqlite
Genome summary form location: /fs/byo/wrighton-data2/home2/projects/DRAM/DRAM_dbs_20200214/genome_summary_form.tsv
ETC module database location: /fs/byo/wrighton-data2/home2/projects/DRAM/DRAM_dbs_20200214/etc_module_database.tsv
Function heatmap form location: /fs/byo/wrighton-data2/home2/projects/DRAM/DRAM_dbs_20200214/function_heatmap_form.tsv
AMG database location: /fs/byo/wrighton-data2/home2/projects/DRAM/DRAM_dbs_20200214/amg_database.tsv
```

**Comment by erikrikarddaniel** [comment]
OK. Can you be more exact, but by example, as to which parameters to set and to what values, and how I then go to a full command. E.g. how do I point out where the UniRef input file is so I can write a command based on the output of `print_config`. (I found this part poorly documented earlier when I wanted to restart the process.)

**Comment by shafferm** [comment]
So based on the `print_config` output above the `set_database_locations` command would look like the command below. So you should be able to use this command but change the directory from `/fs/byo/wrighton-data2/home2/projects/DRAM/DRAM_dbs_20200214/` to wherever you set your `prepare_databases` output directory and replace `20200215` with the date that was put into the file names from your output directory.

Or you can just run `prepare_databases` again. Also make sure you pull the latest changes to the repo and reinstall.

```
DRAM.py set_database_locations --kegg_db_loc /fs/byo/wrighton-data2/home2/projects/DRAM/DRAM_dbs_20200214/kegg.20200215.mmsdb \
                               --uniref_db_loc /fs/byo/wrighton-data2/home2/projects/DRAM/DRAM_dbs_20200214/uniref90.20200215.mmsdb \
                               --pfam_db_loc /fs/byo/wrighton-data2/home2/projects/DRAM/DRAM_dbs_20200214/pfam.mmspro \
                               --pfam_hmm_dat /fs/byo/wrighton-data2/home2/projects/DRAM/DRAM_dbs_20200214/Pfam-A.hmm.dat.gz \
                               --dbcan_db_loc /fs/byo/wrighton-data2/home2/projects/DRAM/DRAM_dbs_20200214/dbCAN-HMMdb-V7.txt \
                               --vogdb_db_loc /fs/byo/wrighton-data2/home2/projects/DRAM/DRAM_dbs_20200214/vog_latest_hmms.txt \
                               --viral_db_loc /fs/byo/wrighton-data2/home2/projects/DRAM/DRAM_dbs_20200214/refseq_viral.20200215.mmsdb \
                               --peptidase_db_loc /fs/byo/wrighton-data2/home2/projects/DRAM/DRAM_dbs_20200214/peptidases.20200215.mmsdb \
                               --description_db_loc /fs/byo/wrighton-data2/home2/projects/DRAM/DRAM_dbs_20200214/description_db.sqlite \
                               --genome_summary_form_loc /fs/byo/wrighton-data2/home2/projects/DRAM/DRAM_dbs_20200214/genome_summary_form.20200215.tsv \
                               --module_step_form_loc /fs/byo/wrighton-data2/home2/projects/DRAM/DRAM_dbs_20200214/module_step_form.20200215.tsv \
                               --function_heatmap_form_loc /fs/byo/wrighton-data2/home2/projects/DRAM/DRAM_dbs_20200214/function_heatmap_form.20200215.tsv \
                               --amg_database_loc /fs/byo/wrighton-data2/home2/projects/DRAM/DRAM_dbs_20200214/amg_database.20200215.tsv \
                               --update_description_db
```

**Comment by erikrikarddaniel** [comment]
Thanks, submitted to the queue.

I think it would be a good idea to have an option that tells the script to look for downloaded files: `--use_downloads` or something.

**Comment by erikrikarddaniel** [comment]
I still get the `OverflowError: string longer than INT_MAX bytes` error (full message below). I have verified that `DRAM.py` is the version I built yesterday evening.

Maybe time for plan B, I'll email you separately about that.

```
Traceback (most recent call last):
  File "/home/daniel/miniconda3/envs/dram/bin/DRAM.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/domus/h1/daniel/dev/DRAM/scripts/DRAM.py", line 172, in <module>
    args.func(**args_dict)
  File "/domus/h1/daniel/dev/DRAM/mag_annotator/database_processing.py", line 362, in set_database_paths
    populate_description_db(db_dict)
  File "/domus/h1/daniel/dev/DRAM/mag_annotator/database_processing.py", line 382, in populate_description_db
    db_handler)
  File "/domus/h1/daniel/dev/DRAM/mag_annotator/database_processing.py", line 328, in check_exists_and_add_to_description_db
    db_handler.add_descriptions_to_database(description_list, name, clear_table=True)
  File "/domus/h1/daniel/dev/DRAM/mag_annotator/database_handler.py", line 27, in add_descriptions_to_database
    self.session.bulk_save_objects([description_class(**i) for i in description_list])
  File "/home/daniel/miniconda3/envs/dram/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2720, in bulk_save_objects
    False,
  File "/home/daniel/miniconda3/envs/dram/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2908, in _bulk_save_mappings
    transaction.rollback(_capture_exception=True)
  File "/home/daniel/miniconda3/envs/dram/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/daniel/miniconda3/envs/dram/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/home/daniel/miniconda3/envs/dram/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2902, in _bulk_save_mappings
    render_nulls,
  File "/home/daniel/miniconda3/envs/dram/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 102, in _bulk_insert
    bookkeeping=return_defaults,
  File "/home/daniel/miniconda3/envs/dram/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1084, in _emit_insert_statements
    c = cached_connections[connection].execute(statement, multiparams)
  File "/home/daniel/miniconda3/envs/dram/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/home/daniel/miniconda3/envs/dram/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/daniel/miniconda3/envs/dram/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/home/daniel/miniconda3/envs/dram/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/daniel/miniconda3/envs/dram/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1478, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/home/daniel/miniconda3/envs/dram/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/home/daniel/miniconda3/envs/dram/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/home/daniel/miniconda3/envs/dram/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
OverflowError: string longer than INT_MAX bytes
```

**Comment by smdabdoub** [comment]
Also still having the issue. Initially reused the same conda environment, pip uninstalled DRAM, pulled from the repo and reinstalled. Then I completely started over with a new environment and same issue.

**Comment by shafferm** [comment]
Okay I figured out the latest issue. It is connected to how MMSeqs stores headers in newer versions than I had been testing with. You both can try pulling the latest version, reinstalling and then running prepare again.

**Comment by shafferm** [comment]
I can confirm that this fix worked on my system. If you could test on yours that would be great.
